<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TaskRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaskRepository extends EntityRepository
{
    /**
     * Method to hidrate entities as arrays for easier comparison
     * @return array
     */
    public function findAllAsArray()
    {
        $qb = $this->createQueryBuilder('t');
        $qb->select('t');

        return $qb->getQuery()->getArrayResult();
    }
}
